name: Gradle Publish to Maven Central

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set outputs
        id: vars
        run: |
          echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Publish to Sonatype
        env:
          CORE_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
          CORE_CHANNEL: release
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: |
          ./gradlew clean publish 
          echo "Version: ${SHORT_COMMIT_HASH}" >> $GITHUB_STEP_SUMMARY