name: Release Maven Central Publication

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      PROJECT_VERSION: ${{ github.event.release.tag_name }}
      PROJECT_CHANNEL: "stable"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish to Sonatype Central Portal
        run: |
          ./gradlew :core:publishToCentralPortal
          ./gradlew :core-paper:publishToCentralPortal
          ./gradlew :core-velocity:publishToCentralPortal
